spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dream-music-db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: myroot
server:
  port: 8081
